/* Generated By:JavaCC: Do not edit this line. Parser.java */
package ca3.yapl.parser;

import ca3.yapl.exceptions.IllegalUseException;
import ca3.yapl.exceptions.ProcedureNameMismatchException;
import ca3.yapl.exceptions.ProgramNameMismatchException;
import ca3.yapl.exceptions.YAPLException;
import ca3.yapl.impl.Symbol;
import ca3.yapl.impl.SymbolTable;
import ca3.yapl.interfaces.ISymbol;
import ca3.yapl.lib.CompilerMessage;
import java.io.FileInputStream;
import java.io.IOException;

public class Parser implements ParserConstants {
    private static SymbolTable symbolTable = new SymbolTable();

    public static void main(String args[]) {
        try {
            Parser parser = new Parser(new FileInputStream(args[0]));
            parser.Program();

            CompilerMessage.printOK("Parser");
        } catch (ParseException pe) {
            CompilerMessage.printError(pe, "Parser");
        } catch (YAPLException ye) {
            CompilerMessage.printError(ye, "Parser");
        } catch (IOException e) {
            System.err.println("something went wrong" + e);
        }
    }

  static final public void RelOp() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      jj_consume_token(LT);
      break;
    case LEQ:
      jj_consume_token(LEQ);
      break;
    case GEQ:
      jj_consume_token(GEQ);
      break;
    case GT:
      jj_consume_token(GT);
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void EqualOp() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
      break;
    case NEQ:
      jj_consume_token(NEQ);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void AddOp() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      jj_consume_token(PLUS);
      break;
    case MINUS:
      jj_consume_token(MINUS);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void MulOp() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULT:
      jj_consume_token(MULT);
      break;
    case DIV:
      jj_consume_token(DIV);
      break;
    case MOD:
      jj_consume_token(MOD);
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Literal() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Selector() throws ParseException, YAPLException {
    Token tIdent;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQUARE_BRACKET_OPEN:
      jj_consume_token(SQUARE_BRACKET_OPEN);
      Expr();
      jj_consume_token(SQUARE_BRACKET_CLOSE);
      break;
    case DOT:
      jj_consume_token(DOT);
      tIdent = jj_consume_token(IDENT);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQUARE_BRACKET_OPEN:
    case DOT:
      Selector();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
  }

  static final public void ArrayLen() throws ParseException, YAPLException {
    Token tIdent;
    jj_consume_token(HASH);
    tIdent = jj_consume_token(IDENT);
            ISymbol s = symbolTable.lookup(tIdent);
            if (s.getKind() != ISymbol.Variable && s.getKind() != ISymbol.Parameter) {
                {if (true) throw new IllegalUseException(s);}
            }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQUARE_BRACKET_OPEN:
    case DOT:
      Selector();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  static final public void PrimaryExpr() throws ParseException, YAPLException {
    Token tIdent;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case NUMBER:
      Literal();
      break;
    case OPEN_PARENTH:
      jj_consume_token(OPEN_PARENTH);
      Expr();
      jj_consume_token(CLOSE_PARENTH);
      break;
    default:
      jj_la1[9] = jj_gen;
      if (jj_2_1(3)) {
        ProcedureCall();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENT:
          tIdent = jj_consume_token(IDENT);
            ISymbol s = symbolTable.lookup(tIdent);
            if (s.getKind() != ISymbol.Variable && s.getKind() != ISymbol.Constant && s.getKind() != ISymbol.Parameter)
                {if (true) throw new IllegalUseException(s);}
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case SQUARE_BRACKET_OPEN:
          case DOT:
            Selector();
            break;
          default:
            jj_la1[8] = jj_gen;
            ;
          }
          break;
        case HASH:
          ArrayLen();
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  static final public void UnaryExpr() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
      AddOp();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    PrimaryExpr();
  }

  static final public void MulExpr() throws ParseException, YAPLException {
    UnaryExpr();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
      case DIV:
      case MOD:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_1;
      }
      MulOp();
      UnaryExpr();
    }
  }

  static final public void AddExpr() throws ParseException, YAPLException {
    MulExpr();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_2;
      }
      AddOp();
      MulExpr();
    }
  }

  static final public void RelExpr() throws ParseException, YAPLException {
    AddExpr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
    case LEQ:
    case GT:
    case GEQ:
      RelOp();
      AddExpr();
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
  }

  static final public void EqualExpr() throws ParseException, YAPLException {
    RelExpr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
    case NEQ:
      EqualOp();
      RelExpr();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  static final public void CondAndExpr() throws ParseException, YAPLException {
    EqualExpr();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_3;
      }
      jj_consume_token(AND);
      EqualExpr();
    }
  }

  static final public void CreationExpr() throws ParseException, YAPLException {
    jj_consume_token(NEW);
    StaticType();
    jj_consume_token(SQUARE_BRACKET_OPEN);
    Expr();
    jj_consume_token(SQUARE_BRACKET_CLOSE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQUARE_BRACKET_OPEN:
      jj_consume_token(SQUARE_BRACKET_OPEN);
      Expr();
      jj_consume_token(SQUARE_BRACKET_CLOSE);
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  static final public void Expr() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case PLUS:
    case MINUS:
    case HASH:
    case OPEN_PARENTH:
    case IDENT:
    case NUMBER:
      CondAndExpr();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OR:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_4;
        }
        jj_consume_token(OR);
        CondAndExpr();
      }
      break;
    case NEW:
      CreationExpr();
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ArgumentList() throws ParseException, YAPLException {
    Expr();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      Expr();
    }
  }

  static final public void ProcedureCall() throws ParseException, YAPLException {
    Token tIdent;
    tIdent = jj_consume_token(IDENT);
            ISymbol s = symbolTable.lookup(tIdent);
            if (s.getKind() != ISymbol.Procedure)
                {if (true) throw new IllegalUseException(s);}
    jj_consume_token(OPEN_PARENTH);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case TRUE:
    case FALSE:
    case PLUS:
    case MINUS:
    case HASH:
    case OPEN_PARENTH:
    case IDENT:
    case NUMBER:
      ArgumentList();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(CLOSE_PARENTH);
  }

  static final public void Assignment() throws ParseException, YAPLException {
    Token tIdent;
    tIdent = jj_consume_token(IDENT);
            ISymbol s = symbolTable.lookup(tIdent);
            if (s.getKind() != ISymbol.Variable && s.getKind() != ISymbol.Parameter)
                {if (true) throw new IllegalUseException(s);}
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQUARE_BRACKET_OPEN:
    case DOT:
      Selector();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(ASSIGN);
    Expr();
  }

  static final public void IfStatement() throws ParseException, YAPLException {
    jj_consume_token(IF);
    Expr();
    jj_consume_token(THEN);
    StatementList();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case THEN:
      jj_consume_token(THEN);
      StatementList();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(ENDIF);
  }

  static final public void WhileStatement() throws ParseException, YAPLException {
    jj_consume_token(WHILE);
    Expr();
    jj_consume_token(DO);
    StatementList();
    jj_consume_token(ENDWHILE);
  }

  static final public void ReturnStatement() throws ParseException, YAPLException {
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case TRUE:
    case FALSE:
    case PLUS:
    case MINUS:
    case HASH:
    case OPEN_PARENTH:
    case IDENT:
    case NUMBER:
      Expr();
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
  }

  static final public void WriteStatement() throws ParseException, YAPLException {
    jj_consume_token(WRITE);
    jj_consume_token(STRING);
  }

  static final public void Statement() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      IfStatement();
      break;
    case WHILE:
      WhileStatement();
      break;
    case RETURN:
      ReturnStatement();
      break;
    case WRITE:
      WriteStatement();
      break;
    default:
      jj_la1[25] = jj_gen;
      if (jj_2_2(3)) {
        Assignment();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENT:
          ProcedureCall();
          break;
        case BEGIN:
        case DECLARE:
          Block();
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  static final public void StatementList() throws ParseException, YAPLException {
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case WRITE:
      case BEGIN:
      case RETURN:
      case DECLARE:
      case IDENT:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_6;
      }
      Statement();
      jj_consume_token(SEMICOLON);
    }
  }

  static final public void Block() throws ParseException, YAPLException {
      symbolTable.openScope(false);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DECLARE:
      Decl();
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    jj_consume_token(BEGIN);
    StatementList();
    jj_consume_token(END);
      symbolTable.closeScope();
  }

  static final public void StaticType() throws ParseException, YAPLException {
    Token tIdent;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
      break;
    case BOOL:
      jj_consume_token(BOOL);
      break;
    case IDENT:
      tIdent = jj_consume_token(IDENT);
            ISymbol s = symbolTable.lookup(tIdent);
            if (s.getKind() != ISymbol.Typename)
                {if (true) throw new IllegalUseException(s);}
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Type() throws ParseException, YAPLException {
    StaticType();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SQUARE_BRACKET_OPEN:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_7;
      }
      jj_consume_token(SQUARE_BRACKET_OPEN);
      jj_consume_token(SQUARE_BRACKET_CLOSE);
    }
  }

  static final public void ReturnType() throws ParseException, YAPLException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VOID:
      jj_consume_token(VOID);
      break;
    case INT:
    case BOOL:
    case IDENT:
      Type();
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ConstDecl() throws ParseException, YAPLException {
    Token tIdent;
    jj_consume_token(CONST);
    tIdent = jj_consume_token(IDENT);
            ISymbol s = new Symbol(tIdent, ISymbol.Constant);
            symbolTable.addSymbol(s);
    jj_consume_token(CONST_ASSIGN);
    Literal();
    jj_consume_token(SEMICOLON);
  }

  static final public void VarDecl() throws ParseException, YAPLException {
    Token tIdent;
    Type();
    tIdent = jj_consume_token(IDENT);
            ISymbol s = new Symbol(tIdent, ISymbol.Variable);
            symbolTable.addSymbol(s);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_8;
      }
      jj_consume_token(COMMA);
      tIdent = jj_consume_token(IDENT);
            s = new Symbol(tIdent, ISymbol.Variable);
            symbolTable.addSymbol(s);
    }
    jj_consume_token(SEMICOLON);
  }

  static final public void TypeDecl() throws ParseException, YAPLException {
    Token tIdent;
    jj_consume_token(RECORD);
    tIdent = jj_consume_token(IDENT);
            ISymbol s = new Symbol(tIdent, ISymbol.Typename);
            symbolTable.addSymbol(s);
            symbolTable.openScope(false);
    label_9:
    while (true) {
      VarDecl();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case BOOL:
      case IDENT:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_9;
      }
    }
            symbolTable.closeScope();
    jj_consume_token(ENDRECORD);
  }

  static final public void Decl() throws ParseException, YAPLException {
    jj_consume_token(DECLARE);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case BOOL:
      case CONST:
      case RECORD:
      case IDENT:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONST:
        ConstDecl();
        break;
      case INT:
      case BOOL:
      case IDENT:
        VarDecl();
        break;
      case RECORD:
        TypeDecl();
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void FormalParam() throws ParseException, YAPLException {
    Token tIdent;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case READONLY:
      jj_consume_token(READONLY);
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
    Type();
    tIdent = jj_consume_token(IDENT);
            ISymbol s = new Symbol(tIdent, ISymbol.Parameter);
            symbolTable.addSymbol(s);
            //TODO: set nex param ?? parent symbol ??

  }

  static final public void FormalParamList() throws ParseException, YAPLException {
    FormalParam();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[37] = jj_gen;
        break label_11;
      }
      jj_consume_token(COMMA);
      FormalParam();
    }
  }

  static final public void Procedure() throws ParseException, YAPLException {
    Token tStartIdent;
    Token tEndIdent;
    jj_consume_token(PROCEDURE);
    ReturnType();
    tStartIdent = jj_consume_token(IDENT);
            ISymbol s = new Symbol(tStartIdent, ISymbol.Procedure);
            symbolTable.addSymbol(s);
            symbolTable.openScope(false);
    jj_consume_token(OPEN_PARENTH);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOL:
    case READONLY:
    case IDENT:
      FormalParamList();
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    jj_consume_token(CLOSE_PARENTH);
    Block();
    tEndIdent = jj_consume_token(IDENT);
            if (!tEndIdent.image.equals(tStartIdent.image)) {if (true) throw new ProcedureNameMismatchException(tStartIdent, tEndIdent);}
            symbolTable.closeScope();
    jj_consume_token(SEMICOLON);
  }

  static final public void Program() throws ParseException, YAPLException {
    Token tStartIdent;
    Token tEndIdent;
    jj_consume_token(PROGRAM);
    tStartIdent = jj_consume_token(IDENT);
            symbolTable.openScope(false);
            ISymbol s = new Symbol(tStartIdent, ISymbol.Program);
            symbolTable.openScope(true);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DECLARE:
      case PROCEDURE:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DECLARE:
        Decl();
        break;
      case PROCEDURE:
        Procedure();
        break;
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(BEGIN);
    StatementList();
    jj_consume_token(END);
    tEndIdent = jj_consume_token(IDENT);
            if (!tEndIdent.image.equals(tStartIdent.image)) {if (true) throw new ProgramNameMismatchException(tStartIdent, tEndIdent);}
            symbolTable.closeScope();
            symbolTable.closeScope();
    jj_consume_token(DOT);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_3_1() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(39)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) return true;
    }
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(NEW)) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(IDENT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(IDENT)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENT)) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(HASH)) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(SQUARE_BRACKET_OPEN)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    }
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(IDENT)) return true;
    if (jj_scan_token(OPEN_PARENTH)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) jj_scanpos = xsp;
    if (jj_scan_token(CLOSE_PARENTH)) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(OPEN_PARENTH)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) return true;
    }
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x22000,0x0,0x0,0x0,0x0,0x22000,0x0,0x0,0x0,0x0,0x0,0x0,0x100,0x0,0x80,0x22800,0x0,0x22800,0x0,0x10000,0x22800,0x10c0020,0x2200000,0x32c0020,0x2000000,0x8400,0x0,0x9400,0x0,0x8400,0xc08400,0xc08400,0x10000000,0x0,0x10008400,0x22000000,0x22000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x1e,0x60,0x180,0xe00,0x8000000,0x5000,0x5000,0x5000,0x5000,0x8010000,0x4008000,0x180,0xe00,0x180,0x1e,0x60,0x0,0x1000,0x0,0xc018180,0x40000,0xc018180,0x5000,0x0,0xc018180,0x0,0x4000000,0x4000000,0x0,0x4000000,0x1000,0x4000000,0x40000,0x4000000,0x4000000,0x4000000,0x0,0x40000,0x4000000,0x0,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[62];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 62; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
